# -*- coding: utf-8 -*-
"""TP09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-gwwP1glM5gRwArzdaqr834kXk-Zl78i

## **Tugas Praktikum 09**
"""

class Human:
  def __init__(self, name, position):
    self.name = name
    self.__position = position
    self._speed = 1

  def setPosition(self, setPosition):
    self.__position = setPosition
  
  def getPosition(self):
    return self.__position
  
  def getSpeed(self):
    return self._speed
  
  def movement(self, direction):
    if direction == 'R':
      move = self.getPosition() + self._speed
    elif direction == 'L':
      move = self.getPosition() - self._speed
    self.setPosition(move)

class Hero(Human):
  def __init__(self, name, position):
    super().__init__(name, position)
    self._power = 15
    self._health = 400
    self._armor = 15
    self._speed = 3
  
  def attack(self, target):
    target._health = target._health - self._power
  
  def getPower(self):
    return self._power

  def getHealth(self):
    return self._health
    
  def getArmor(self):
    return self._armor

class Warrior(Hero):
  def __init__(self, name, position):
    super().__init__(name, position)
    self._power = 26
    self._armor = 30
  
  def special(self, target):
    self._armor = 45
    self._power = 32
    target._health = target._health - self._power

class Assassin(Hero):
  def __init__(self, name, position):
    super().__init__(name, position)
    self._power = 35
    self._speed = 4
  
    def special(self, target):
      self._speed = 7
      self._power = 42
      target._health = target._health - self._power

class Support(Hero):
  def __init__(self, name, position):
    super().__init__(name, position)
    self._health = 500
    self._armor = 8
    self._speed = 4
  
  def special(self, target):
    self._speed = 6
    target._health = target._health + 150
